name: CI .NET con NUnit

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore ExamenChopo.sln

    - name: Compilar proyecto
      run: dotnet build ExamenChopo.sln --no-restore

    - name: Ejecutar Pruebas Unitarias
      run: dotnet test ExamenChopo.sln --no-build --verbosity normal
